# Generated by Django 3.1.1 on 2020-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст задачи'),
        ),
    ]
