# Generated by Django 3.1.1 on 2020-09-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200924_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_date',
        ),
    ]
