# Generated by Django 3.1.1 on 2020-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200924_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2020-09-25', null=True, verbose_name='Исполнить до'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=140, verbose_name='заголовок'),
        ),
    ]
