# Generated by Django 3.1.1 on 2020-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200926_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default='2020-09-26', null=True, verbose_name='Исполнить до'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('к выполнению', 'к выполнению'), ('выполняется', 'выполняется'), ('выполнено', 'выполнено'), ('отменено', 'отменено')], default='к выполнению', max_length=20, verbose_name='статус'),
        ),
    ]
